app_name = "wiki_pdf"
app_title = "Wiki PDF"
app_publisher = "User"
app_description = "Custom App for Wiki PDF Download"
app_icon = "octicon octicon-file-directory"
app_color = "grey"
app_email = "user@example.com"
app_license = "MIT"

web_include_js = "/assets/wiki_pdf/js/wiki_pdf.js"
